//! `ob-gui` — the Figura Obscura desktop application.
//!
//! On Windows this is a GUI-subsystem binary (see the `windows_subsystem`
//! attribute) so launching it from a shortcut does not also open a console
//! window behind it.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod downloads;
mod pages;
mod prefs;
mod run;
/// Software UI renderer used by the screenshot tests (never shipped).
#[cfg(test)]
mod screenshot;
mod theme;

use app::ObApp;

/// The window icon, as raw RGBA generated by `cargo xtask icons`.
///
/// Raw rather than PNG so the app needs no image decoder at startup purely to
/// put a picture on its own title bar.
const WINDOW_ICON: &[u8] = include_bytes!("../../../packaging/assets/window-icon-256.rgba");
const WINDOW_ICON_SIZE: u32 = 256;

fn main() -> eframe::Result<()> {
    if std::env::args()
        .skip(1)
        .any(|a| a == "--version" || a == "-V")
    {
        // Hand-rolled rather than pulling clap into the GUI for one flag. On
        // Windows this is a GUI-subsystem binary with no console attached, so
        // nothing appears there — the About page carries the same string.
        println!("obscura-gui {}", ob_core::version::LONG);
        // Which providers this build has, for the same reason the CLI prints
        // them: a CPU-only build and a GPU one are otherwise identical from the
        // outside, and the only symptom of the wrong one is a slow job.
        println!("\nexecution providers (in preference order):");
        for line in ob_detect::session::execution_provider_report() {
            println!("  {line}");
        }
        if !ob_detect::gpu_support_compiled_in() {
            println!("\nThis is a CPU-only build: no GPU execution provider was compiled in.");
        }
        return Ok(());
    }

    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title(format!("Figura Obscura {}", env!("CARGO_PKG_VERSION")))
            .with_inner_size([1180.0, 820.0])
            // Below this the two-column Tuning page starts clipping controls.
            .with_min_inner_size([940.0, 620.0])
            .with_icon(window_icon()),
        ..Default::default()
    };

    eframe::run_native(
        "figura-obscura",
        options,
        Box::new(|cc| {
            theme::install(&cc.egui_ctx);
            Ok(Box::<ObApp>::default())
        }),
    )
}

fn window_icon() -> egui::IconData {
    // A wrong-sized blob would be a build error waiting to happen at runtime,
    // so fall back to no icon rather than panicking on startup.
    let expected = (WINDOW_ICON_SIZE * WINDOW_ICON_SIZE * 4) as usize;
    if WINDOW_ICON.len() != expected {
        return egui::IconData::default();
    }
    egui::IconData {
        rgba: WINDOW_ICON.to_vec(),
        width: WINDOW_ICON_SIZE,
        height: WINDOW_ICON_SIZE,
    }
}
